### ISSUE TITLE
InternalOAuthError: Failed to obtain access token

### ISSUE THREAD

**Issue by angelhodar** [mystery-man/passport-tiktok#1]
Hey @mystery-man , thanks for creating this strategy! I have tested it and the problem is that it throws this error:

```2022-06-02T08:52:31.057517+00:00 app[web.1]: InternalOAuthError: Failed to obtain access token
2022-06-02T08:52:31.057518+00:00 app[web.1]:     at Strategy.OAuth2Strategy._createOAuthError (/app/node_modules/passport-oauth2/lib/strategy.js:423:17)
2022-06-02T08:52:31.057519+00:00 app[web.1]:     at /app/node_modules/passport-tiktok-auth/lib/passport-tiktok/strategy.js:217:74
2022-06-02T08:52:31.057519+00:00 app[web.1]:     at /app/node_modules/oauth/lib/oauth2.js:209:7
2022-06-02T08:52:31.057520+00:00 app[web.1]:     at passBackControl (/app/node_modules/oauth/lib/oauth2.js:134:9)
2022-06-02T08:52:31.057521+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/oauth/lib/oauth2.js:157:7)
2022-06-02T08:52:31.057521+00:00 app[web.1]:     at IncomingMessage.emit (node:events:539:35)
2022-06-02T08:52:31.057522+00:00 app[web.1]:     at endReadableNT (node:internal/streams/readable:1345:12)
2022-06-02T08:52:31.057522+00:00 app[web.1]:     at processTicksAndRejections (node:internal/process/task_queues:83:21)```

This logs comes from a heroku server I have had to create as tiktok doesnt accept localhost as callback url or redirect domain even if its https (either with the port syntax). I would like to test on localhost to discard any possible heroku proxy error or something like that but its not possible. How did you manage to test on localhost?

Thanks in advance!!

**Comment by mystery-man** [comment]
Hey @angelhodar,

You are right. Localhost can't be used over there with https as well. You can try ngrok.io as well if it is a paid option otherwise it will expire in like 8 hours or so and that wont work as the verification of redirect url takes a day.

This is how I solved the issue and make it work on Localhost.

I have the oauth process deployed on the subdomain and not the redirect url route.

What I did was that I redirected the initial oauth request to the hosted subdomain which was `https://subdomain.domain.com/oauth/v1/tiktok`
and after authentication it was redirected to the redirectUrl (which was not on that server and that gave a 404). I copied that and replaced the url with my localhost one. That way I was able to make it work for the localhost.

**Comment by angelhodar** [comment]
Thanks for your answer! I have tested by implementing it manually as they said in the docs and now it works. Maybe they have broken your package with some update?

**Comment by mystery-man** [comment]
I've just checked out again and oauth process is working perfectly fine for me. I am also using it in a production environment. Maybe some issues with your installed package?
You are using the latest v1.0.3 right?

**Comment by angelhodar** [comment]
It was the latest (fresh install this morning). Who knows, probably something related to Heroku proxy or something like that. Tbh I have implemented it in 10 minutes with the examples that tiktok puts in the documentation so I am fine. Anyway thanks for creating this strategy, the passport library needs more updates in community strategies...

**Comment by mystery-man** [comment]
Ohh, I see. Well it's all good now that you've implemented the Auth process and that's what matters :).
Agreed with you on the Passport Library part. Will try to contribute in it as well 💯
